framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'zh_CN'
    translator:
        fallbacks: ['zh_CN']
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

knp_paginator:
    template:
        pagination: 'sliding.html.twig'

stof_doctrine_extensions:
    default_locale: zh_CN
    translation_fallback: true
    orm:
        default:
            tree: true
            timestampable: true
            blameable: true
            translatable: true
            sortable: true
            sluggable: true

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        # the name of the "filter set"
        post_listImage:

            # adjust the image quality to 75%
            quality: 75

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 90], mode: outbound }

                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                background: { size: [124, 94], position: center, color: '#555555' }
        wall_painting_cover:
            filters:
                thumbnail: { size: [225, 148], mode: outbound  }
        advertisement_cover:
            filters:
                thumbnail: { size: [1600, 500] }
        category_icon:
            filters:
                thumbnail: { size: [200, 132] }
        customer_logo:
            filters:
                thumbnail: { size: [188, 155], mode: outbound }
        artist_figure_sm:
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
        artist_figure_lg:
            filters:
                thumbnail: { size: [320, 320], mode: outbound }
        message_cover:
            filters:
                thumbnail: { size: [110, 76], mode: outbound }

vich_uploader:
    db_driver: orm

    mappings:
        media_file:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer: vich.date_directory_namer

phpmob_settings:
    schemas:
        homepage:
            label: section.homepage.label
            settings:
                page_title_zh_CN:
                    label: page.title.zh_CN
                page_meta_description_zh_CN:
                    label: page.meta.description.zh_CN
                page_meta_keywords_zh_CN:
                    label: page.meta.keywords.zh_CN
                page_title_en:
                    label: page.title.en
                page_meta_description_en:
                    label: page.meta.description.en
                page_meta_keywords_en:
                    label: page.meta.keywords.en
                advertisement_limit:
                    label: advertisement.limit
                    value: 6
                wall_painting_row_limit:
                    label: wallPainting.rowLimit
                    value: 4
                wall_painting_category_row_limit:
                    label: wallPaintingCategory.rowLimit
                    value: 2
                customer_row_limit:
                    label: customer.rowLimit
                    value: 2
                message_row_limit:
                    label: message.rowLimit
                    value: 2
                artist_row_limit:
                    label: artist.rowLimit
                    value: 1
        wall_painting_index:
            label: section.wallPaintingIndex.label
            settings:
                page_title_zh_CN:
                    label: page.title.zh_CN
                page_meta_description_zh_CN:
                    label: page.meta.description.zh_CN
                page_meta_keywords_zh_CN:
                    label: page.meta.keywords.zh_CN
                page_title_en:
                    label: page.title.en
                page_meta_description_en:
                    label: page.meta.description.en
                page_meta_keywords_en:
                    label: page.meta.keywords.en